---
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: backupjob
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backupjob-secret-reader
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs: ['get', 'list']
